install.packages("ggplot2")
library(ggplot2)
install.packages("lattice")
library(lattice)
install.packages("plyr")
library(plyr)
install.packages("dplyr")
library(dplyr)
install.packages("caret")
library(caret)
install.packages("tidyverse")
library(tidyverse)
install.packages("corrplot")
library(corrplot)
install.packages("colorspace")
library(colorspace)
install.packages("keras")
library(keras)
install.packages("randomForest")
library(randomForest)
install.packages("kableExtra")
library(kableExtra)
install.packages("modelr")
library(modelr)
install.packages("psych")
library(psych)
install.packages("Rmisc")
library(Rmisc)
install.packages("gridExtra")
library(gridExtra)
install.packages("scales")
library(scales)
install.packages("rpart")
library(rpart)
install.packages("broom")
library(broom)
install.packages("yardstick")
library(yardstick)
winequality <- read.csv("http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv", sep = ";")
head(winequality)
summary(winequality)

install.packages("ggplot2")
library(ggplot2)
ggplot(winequality, aes(x = alcohol)) + geom_histogram(fill = "red", bindwith = 1)
numericVars <- which(sapply(winequality, is.numeric))
numericVarNames <- names(numericVars)
cat("There are", length(numericVars), "numeric variables")
install.packages("corrplot")
library(corrplot)
all_numVar <- winequality[, numericVars]
cor_numVar <- cor(all_numVar, use = "pairwise.complete.obs")
cor_sorted <- as.matrix(sort(cor_numVar[,"alcohol"], decreasing = TRUE))
Cor_High <- names(which(apply(cor_sorted, 1, function(x) abs(x) > 0.175)))
cor_numVar <- cor_numVar[Cor_High, Cor_High]
corrplot.mixed(cor_numVar, tl.col = "black", tl.pos = "lt")
ggplot(winequality, aes(x = quality, y = alcohol)) + geom_point(col = "green") + labs(x = "\n Quality \n") + labs(y = "\n Alcohol by Volume \n") + geom_smooth(method = "lm", se = FALSE, color = "red", aes(group = 1))
cor(winequality$alcohol, winequality$fixed.acidity, use = "pairwise.complete.obs")
cor(winequality$alcohol, winequality$volatile.acidity, use = "pairwise.complete.obs")
cor(winequality$alcohol, winequality$citric.acid, use = "pairwise.complete.obs")
cor(winequality$alcohol, winequality$residual.sugar, use = "pairwise.complete.obs")

cor(winequality$alcohol, winequality$chlorides, use = "pairwise.complete.obs")
cor(winequality$alcohol, winequality$free.sulfur.dioxide, use = "pairwise.complete.obs")
cor(winequality$alcohol, winequality$total.sulfur.dioxide, use = "pairwise.complete.obs")
cor(winequality$alcohol, winequality$density, use = "pairwise.complete.obs")
cor(winequality$alcohol, winequality$pH, use = "pairwise.complete.obs")
cor(winequality$alcohol, winequality$sulphates, use = "pairwise.complete.obs")
cor(winequality$alcohol, winequality$quality, use = "pairwise.complete.obs")
ggplot(winequality, aes(x = pH, y = alcohol)) + geom_point(col = "pink") + labs(x = "\n pH content \n") + labs(y = "\n Alcohol by Volume \n") + geom_smooth(method = "lm", se = FALSE, color = "red", aes(group = 1))
ggplot(winequality, aes(x = citric.acid, y = alcohol)) + geom_point(col = "pink") + labs(x = "\n Citric Acid \n") + labs(y = "\n Alcohol by Volume \n") + geom_smooth(method = "lm", se = FALSE, color = "red", aes(group = 1))
ggplot(winequality, aes(x = fixed.acidity, y = alcohol)) + geom_point(col = "black") + labs(x = "\n Fixed Acidity in the wine \n") + labs(y = "\n Alcohol by Volume \n") + geom_smooth(method = "lm", se = FALSE, color = "red", aes(group = 1))
ggplot(winequality, aes(x = volatile.acidity, y = alcohol)) + geom_point(col = "blue") + labs(x = "\n Volatile Acidity \n") + labs(y = "\n Alcohol by Volume \n") + geom_smooth(method = "lm", se = FALSE, color = "red", aes(group = 1))
ggplot(winequality, aes(x = residual.sugar, y = alcohol)) + geom_point(col = "blue") + labs(x = "\n Residual Sugar Content \n") + labs(y = "\n Alcohol by Volume \n") + geom_smooth(method = "lm", se = FALSE, color = "red", aes(group = 1))
ggplot(winequality, aes(x = chlorides, y = alcohol)) + geom_point(col = "blue") + labs(x = "\n Chlorides in wine \n") + labs(y = "\n Alcohol by Volume \n") + geom_smooth(method = "lm", se = FALSE, color = "red", aes(group = 1))
ggplot(winequality, aes(x = free.sulfur.dioxide, y = alcohol)) + geom_point(col = "blue") + labs(x = "\n Free Sulfur Dioxide \n") + labs(y = "\n Alcohol by Volume \n") + geom_smooth(method = "lm", se = FALSE, color = "red", aes(group = 1))
ggplot(winequality, aes(x = total.sulfur.dioxide, y = alcohol)) + geom_point(col = "blue") + labs(x = "\n Total Sulfur Dioxide \n") + labs(y = "\n Alcohol by Volume \n") + geom_smooth(method = "lm", se = FALSE, color = "red", aes(group = 1))
ggplot(winequality, aes(x = density, y = alcohol)) + geom_point(col = "blue") + labs(x = "\n Density \n") + labs(y = "\n Alcohol by Volume \n") + geom_smooth(method = "lm", se = FALSE, color = "red", aes(group = 1))
ggplot(winequality, aes(x = sulphates, y = alcohol)) + geom_point(col = "violet") + labs(x = "\n Sulphates \n") + labs(y = "\n Alcohol by Volume \n") + geom_smooth(method = "lm", se = FALSE, color = "red", aes(group = 1))

index <- 1:68
training <- winequality[index,]
testing <- winequality[-index,]
training %>%
  mutate_at(vars(-alcohol), scale) -> training 
testing %>%
  
  mutate_at(vars(-alcohol), scale) -> testing
remove.packages("dplyr")
install.packages("dplyr")
library(dplyr)
index <- 1:68
training <- winequality[index,]
testing <- winequality[-index,]
training %>%
  mutate_at(vars(-alcohol), scale) -> training 
fit_lm <- lm(alcohol~., data = training)
summary(fit_lm)
pred_lm <- predict(fit_lm, newdata = testing)
print(head(pred_lm))
fit_rf <- randomForest(alcohol~., data = training)
install.packages("randomForest")
library(randomForest)
fit_rf <- randomForest(alcohol~., data = training)
summary(fit_rf)
pred_rf <- predict(fit_rf, newdata = testing)
print(head(pred_rf))
install.packages("rpart")
library(rpart)
fit_rpart <- rpart(alcohol~., data = training)
summary(fit_rpart)
pred_rpart <- predict(fit_rpart, data = testing)
print(head(pred_rpart))
